# @format

BOT:
  OWNERS: ["948937171031695411"]
  ADMINS: ["948937171031695411","948937171031695411"]

LINKS:
  SUPPORT: "https://discord.com/invite/UFuhyzhrbX"
  MONGO_URI: "mongodb+srv://Securebot:X8MxCyPNBFt8U9Yu@cluster0.g6pwm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "98f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "956742214770368532"
  TOKEN: ""

FUEGO:
  PREFIX: ","
  EMOJIS: "black"
  COLOR: "#FF0000"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: "https://discord.com/invite/UFuhyzhrbX"


WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1243797361269149697/Jd5_YCbswervPwG50i5i20i77IiDkPYly6sPdgZNgSDrPaKemneL4nHjUCqfhVcBgRSJ"
  STATIC: "https://discord.com/api/webhooks/1243797361269149697/Jd5_YCbswervPwG50i5i20i77IiDkPYly6sPdgZNgSDrPaKemneL4nHjUCqfhVcBgRSJ"
  PLAYER: "https://discord.com/api/webhooks/1243797361269149697/Jd5_YCbswervPwG50i5i20i77IiDkPYly6sPdgZNgSDrPaKemneL4nHjUCqfhVcBgRSJ"
  SERVER: "https://discord.com/api/webhooks/1243797361269149697/Jd5_YCbswervPwG50i5i20i77IiDkPYly6sPdgZNgSDrPaKemneL4nHjUCqfhVcBgRSJ"
  COMMAND: "https://discord.com/api/webhooks/1243797361269149697/Jd5_YCbswervPwG50i5i20i77IiDkPYly6sPdgZNgSDrPaKemneL4nHjUCqfhVcBgRSJ"
